defaults:
  - _self_
  - recipe: ???

output: "learn_quant/outputs/"

mode: 
  - generate

save: true
time_trial_log: M${universe.m_size}_X${universe.x_size}_D${grammar.depth}_idx-${grammar.indices}.csv

measures:
  target: "M4/X4/d3"
  monotonicity:
    - all