n_runs: 2

expressions:
  n_limit: 5
  x_size: 8
  m_size: 4
  depth: 3
  output_dir: examples/learn_quant/outputs/
  representation: one_hot
  downsampling: true
  batch_size: 64
  split: 0.8

training:
  device: c
  epochs: 10

model:
  _partial_: true
  _target_: learn_quant.training.MV_LSTM

optimizer:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 1e-2

criterion:
  _target_: torch.nn.BCEWithLogitsLoss
