defaults:
  - _self_
  - model: ???

notes: |
  This run is to evaluate the neural learning quantifiers and logging in MLFlow.

expressions:
  n_limit: 2
  x_size: 8
  m_size: 4
  depth: 3
  output_dir: src/examples/learn_quant/outputs/
  representation: one_hot
  downsampling: true
  generation_args:
    batch_size: 1000
    n_limit: 5000 # Minimum number of sample rows in dataset for a single class. Full dataset length is 2 * n_limit.
    M_size: 4
    X_size: 8
    entropy_threshold: 0.02
    inclusive: False
  batch_size: 64
  split: 0.8

training:
  strategy: kfold
  k_splits: 5
  n_runs: 1
  lightning: true
  device: cpu
  epochs: 10
  conditions: false
  early_stopping:
    monitor: val_loss
    min_delta: 0.001
    patience: 30
    mode: min
    check_on_train_epoch_end: false

optimizer:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 1e-3

criterion:
  _target_: torch.nn.BCEWithLogitsLoss
