# @package _global_
defaults:
  - _self_

name: base

grammar: 
  depth: ${grammar.depth}
  indices: ${grammar.indices}
  weight: ${grammar.weight}

universe:
  m_size: ${universe.m_size}
  x_size: ${universe.x_size}
  inclusive_universes: ${universe.inclusive_universes}

