num_states: 4
num_signals: 4
reward_amount: 1
num_rounds: 4000
prior_over_states: uniform # 'uniform' or 'random'
random_seed: 42
paths:
  weights: outputs/four/weights.txt
  languages: outputs/four/languages.yml  
  accuracy_plot: outputs/four/accuracy.png
  complexity_plot: outputs/four/complexity.png
  tradeoff_plot: outputs/four/tradeoff.png
  prior_plot: outputs/four/prior.png
