num_states: 2
num_signals: 2
reward_amount: 1
num_rounds: 100
prior_over_states: uniform # 'uniform' or 'random'
random_seed: 42
paths:
  weights: outputs/two/weights.txt
  languages: outputs/two/languages.yml
  accuracy_plot: outputs/two/accuracy.png
  complexity_plot: outputs/two/complexity.png
  tradeoff_plot: outputs/two/tradeoff.png
  prior_plot: outputs/two/prior.png
