name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: ""
      - name: set get remote
        run: git remote set-url origin https://github.com/CLMBRs/altk.git
      - name: check for changes
        run: git status
      - name: add name to repo
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Update after linting"
      - name: fetch from main
        run: git fetch origin main
      - name: push code to main
        run: git push origin HEAD:main
